### ISSUE TITLE
Add translation for entire app

### ISSUE THREAD

**Issue by whitef0x0** [whitef0x0/tellform#103]
@lalop can you do this?

**Comment by lalop** [comment]
I started to answer on gitter, I will not be able of adding more then french and english translation but is better than nothing

**Comment by lalop** [comment]
by admin-form you mean this https://github.com/whitef0x0/tellform/tree/master/public/modules/forms/admin ?

**Comment by whitef0x0** [comment]
@lalop yep. Well translation for entire app essentially.

**Comment by whitef0x0** [comment]
@lalop it would be awesome if you could add your client to new list of users on the README. Would help add confidence to new/potential users

**Comment by whitef0x0** [comment]
@lalop I added translation to the entire app. Can you add french?

**Comment by lalop** [comment]
@whitef0x0 sure, I don't find the english translation file, did you do it on stage branch ?

**Comment by whitef0x0** [comment]
Yep

**Comment by whitef0x0** [comment]
@lalop translation is now live on master branch as well

**Comment by lalop** [comment]
hi @whitef0x0, for the translate it's better to use dynamic variable like here https://github.com/whitef0x0/tellform/blob/master/public/modules/forms/base/config/i18n/french.js#L11 then split the sentences.
It's make more sense for the translator and it's more powerfull

**Comment by whitef0x0** [comment]
@lalop oh ok. I didn't know that was possible
