### ISSUE TITLE
intégration issue with long option

### ISSUE THREAD

**Issue by lalop** [whitef0x0/tellform#110]
The actuel design for multi choice question is broken for option with long text 
<img width="1012" alt="capture d ecran 2016-06-11 a 22 55 43" src="https://cloud.githubusercontent.com/assets/313117/15987423/2ab0bc00-3028-11e6-8273-735c6b1e37b3.png">

**Comment by whitef0x0** [comment]
You can fix this by removing the bootstrap col class to make it autofit.

**Comment by whitef0x0** [comment]
Or by adding text-break option to be true

**Comment by whitef0x0** [comment]
I reccomend the latter

**Comment by lalop** [comment]
Do you want me to make a PR ?

**Comment by whitef0x0** [comment]
yea that would be nice
