### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by whitef0x0** [whitef0x0/tellform#113]
I'm thinking of writing a blog post about the underlying tech in tellform. @lalop you interested in contributing or writing your own post
?

**Comment by lalop** [comment]
Hello David,

I’m not sure to have necessary time to write a post for now but I will contribute with pleasure.
More once the form-angular project is ready ( bower => npm, make it a real library, add some doc …. ) I will try to write something on it

**Comment by AdrianP-** [comment]
Really useful!
