### ISSUE TITLE
Problem with analyze

### ISSUE THREAD

**Issue by AdrianP-** [whitef0x0/tellform#120]
Some commit broke Analyze. When finish a form, and try to view the Analyze, this happen:

![captura de pantalla de 2016-06-21 21-41-09](https://cloud.githubusercontent.com/assets/8615608/16243769/232e04dc-37f9-11e6-95b0-305c6736d53c.png)

The file in the log is: submit-form.client.directive.js
And all of this logs print it when makes a scroll on the page

**Comment by AdrianP-** [comment]
In fact, the problem is ".activeField" doesn't exist

**Comment by AdrianP-** [comment]
Other problem is you can't do a "Form" if you're logged

**Comment by whitef0x0** [comment]
@AdrianP- what do you mean by do a Form?

**Comment by whitef0x0** [comment]
Like submit a form if you are logged in?

**Comment by AdrianP-** [comment]
With "do a Form" I meant the option "View Form" in the Admin panel. 
That happens me also with the last commit. Can you test it?

**Comment by whitef0x0** [comment]
@AdrianP- just to clarify this bug only happens when you are logged in, correct?

**Comment by AdrianP-** [comment]
Exactly. Thanks for your time @whitef0x0

**Comment by whitef0x0** [comment]
@AdrianP- what file is this bug referencing?

**Comment by whitef0x0** [comment]
Technically in the analyze view there should be no element with the 'activeField' class so it should be erroring. I haven't had s chance to test this yet

**Comment by AdrianP-** [comment]
The file: 
![tellform](https://cloud.githubusercontent.com/assets/8615608/16467678/b27cf5f8-3e48-11e6-9d66-e1970c60fe41.png)

First Error happens when press the "View Form" button and you're logged.
The second, when you scroll in the Analyze tab

Thanks!
