### ISSUE TITLE
Beautiful work! Minor nitpick though...

### ISSUE THREAD

**Issue by campbx** [whitef0x0/tellform#122]
Great job with the Tellform code David!  Phenomenal job with the UI.

I noticed that multiple choice look a little wonky, and was showing old-fashioned radio buttons on top of your CSS design.  

By the way, one more feature suggestion: If a required field it not complete, form should not be able to progress to the next question.  Right now I can hit enter 5 times and get 5 errors for all skipped fields.  It is better to force me to deal with a required field before moving on.  

Thanks!

**Comment by whitef0x0** [comment]
@campbx I fixed the multiple choice wonky ui design.

**Comment by whitef0x0** [comment]
I just haven't had time to updated it to www.tellform.com

**Comment by campbx** [comment]
Thanks!  Any thoughts on required fields before moving on to the next question?

**Comment by whitef0x0** [comment]
I think it's a good feature. I have a lot on my plate rb but will try to get to it as well as the previous iaaue by the end of the week
