### ISSUE TITLE
Feature request: Offline access to forms from mobile browsers

### ISSUE THREAD

**Issue by jackrabb1t** [whitef0x0/tellform#126]
Is it possible to use html5 local storage or any other means to store the data locally without internet access.

A use-case I am looking at involves using android devices to collect data remotely in locations where network access is hard to get. It would be great to use a Chrome browser, store the data locally and sync up once the connectivity is back, or when manually triggered.

What would it take for this functionality? TIA!!

**Comment by whitef0x0** [comment]
Yea should be possible. The forms are stored in a JSON format so would be pretty easy.

**Comment by jackrabb1t** [comment]
i found this : https://github.com/paldepind/synceddb

I will try to see how one can sync to a postgres db when there is a connection, and how to check from time to time.. any tips/pointers appreciated.

**Comment by whitef0x0** [comment]
@jackrabb1t why not just use HTML5 LocalStorage or equivalent?

**Comment by jackrabb1t** [comment]
@whitef0x0  : If I store this locally, then I still need to sync the data to the server at some point? Please point me to some resources on LocalStorage.

i am a JS/FE newbie, so feeling my way around... synceddb seems to extend IndexedDB to provide exactly what I need?

Another option would be to replace mongoose with something like sequelize, and check if the internet is up. If it is, then just save to db

If not, store offline and then queue it up similar to this example : http://blog.jthoenes.net/2014/04/07/html5-offline-upload-of-images/

thoughts?

**Comment by whitef0x0** [comment]
@jackrabb1t you can move to sequelize but it will be a lot of work.

**Comment by whitef0x0** [comment]
@jackrabb1t Why not just make the frontend into a hybrid app or something

**Comment by jackrabb1t** [comment]
@whitef0x0 

> you can move to sequelize but it will be a lot of work.

yes, it is not the first option

> Why not just make the frontend into a hybrid app or something

Could you please expand on this?

**Comment by whitef0x0** [comment]
@jackrabb1t look into hybrid webapps.

**Comment by whitef0x0** [comment]
Have you made any progress @jackrabb1t? Otherwise I'll just close this issue.

**Comment by mdumrauf** [comment]
@whitef0x0 do you have any plans on implementing this feature in the short or mid term? Need any help?

**Comment by whitef0x0** [comment]
@mdumrauf don't have the time right now to implement this feature but I'll support you in anyway I can if you decide to take it on
