### ISSUE TITLE
Filled out forms are not shown in the analytics

### ISSUE THREAD

**Issue by forteller** [whitef0x0/tellform#127]
I created a test-form and filled it out. But even after waiting 15 minutes the analytics still show 0 responses, and the text I filled out is not shown in the response table. I tried filling it out again, with the same result. 

Here's my test: https://forteller.tellform.com/#!/forms/57c1b44c112b10f82d1aea10

**Comment by whitef0x0** [comment]
I'll look into this.

**Comment by forteller** [comment]
Thanks! Just to make sure I checked again now, and there's still nothing there.

**Comment by whitef0x0** [comment]
@fortweller this has been fixed
