### ISSUE TITLE
Missing Thank You Page & Embed code

### ISSUE THREAD

**Issue by xtremewebsites** [whitef0x0/tellform#128]
After testing the software I noticed a critical issue. There is NO way to add a custom thank you message or  URL redirect upon submission. Also I don't see any way to embed this form. See 
https://goo.gl/IP7mL4  I don't see how this can be used without these 2 things. Please update.

**Comment by whitef0x0** [comment]
@xtremewebsites embedding can be created by just using an iframe with the url of your form.

**Comment by xtremewebsites** [comment]
ok, how about the thank you page. How do you add it or how do you create a
url redirect?

**Comment by whitef0x0** [comment]
It's not customizable

**Comment by johnnymatson** [comment]
Hi @whitef0x0, embedding doesn't work for the URL of the form. Is there a particular format or syntax you would recommend? I tried Embedly but that only renders a card linking back to the page rather than rendering the form itself.

**Comment by whitef0x0** [comment]
@johnnymatson it should work now
