### ISSUE TITLE
preset list of fields

### ISSUE THREAD

**Issue by cantiere** [whitef0x0/tellform#129]
We'd like to inject a pre-set list of fields that users can add to the form.  It's mostly to facilitate integration with the CRM. 

We can definitely get in there to customize, but wondering how complex/easy that would be.

For example in addition to the current list of "add new field" we'd have another section called "Prospects Fields", etc...

**Comment by whitef0x0** [comment]
@cantiere wouldn't be that hard

**Comment by whitef0x0** [comment]
You just need to add a button that adds multiple fields at once instead of one

**Comment by cantiere** [comment]
Thanks! We'll take a look soon. One thing that's frustrating of all form solutions out there is that none allows you to pre-define a list of acceptable fields.

**Comment by whitef0x0** [comment]
@cantiere if you need help customizing tellform to your app I do contract development as well. My email is on my github profile
