### ISSUE TITLE
Bower install error

### ISSUE THREAD

**Issue by sako9** [whitef0x0/tellform#131]
When running bower install I get this error:
bower js-xlsx#0.8.14                            ENORESTARGET No tag found that was able to satisfy 0.8.14

**Comment by sako9** [comment]
the tableExport.jquery.plugin dependency seems to be causing the error

**Comment by whitef0x0** [comment]
@sako9 I'll look into it after my midterm on Tuesday

**Comment by whitef0x0** [comment]
@sako9 can you provide the entire console output as well as details about your system and the version of node that you're running?

**Comment by sako9** [comment]
Had actually uninstalled awhile ago.  When I reinstalled and ran the command, it completed with no error. Guess I was doing something wrong.
