### ISSUE TITLE
tellform.com: no result and analytics saved

### ISSUE THREAD

**Issue by jazzcrack** [whitef0x0/tellform#139]
I just created a form on tellform.com and finished it successful.
No submitted data is saved, na analytics are saved too.
Tried with Chrome 54.0.2840.71 (mac) and Safari 10.0.1 (mac).

**Comment by whitef0x0** [comment]
@jazzcrack I've fixed the no results problem. Will push to the live site soon.

**Comment by whitef0x0** [comment]
I'll take a look at the analytics problem

**Comment by whitef0x0** [comment]
This has been fixed and pushed to the master branch
