### ISSUE TITLE
Broke site after login - Keeps requesting GET http://127.0.0.1:3000/forms 401 (Unauthorized)

### ISSUE THREAD

**Issue by asmarius** [whitef0x0/tellform#144]
Hi,

I followed the [instructions ](https://github.com/whitef0x0/tellform/blob/master/README.md) to install the latest version of Tellform on my machine (no docker installation). After accessing http://127.0.0.1:3000/ and logging in into my account the site seems to be broke. 

My browser console keeps printing

`GET http://127.0.0.1:3000/forms 401 (Unauthorized)
intercepted rejection of  /forms 401
/forms`.

The address in the statusbar is constantly switching from http://127.0.0.1:3000/forms to http://127.0.0.1:3000/signin and back again.

Clicking the "+" button opens a red input form for less than a second before it disappears again.

It seems to be the same issue users are facing in the project's [gitter chat](https://gitter.im/whitef0x0/tellform). 

Browser: Google Chrome 55.0.2883.87

Thanks

**Comment by whitef0x0** [comment]
@asmarius you have to use a subdomain. Please setup DNSMasq to use it properly. Also you need to set the BASE_URL in the config to whatever your domain will be.

**Comment by ersel** [comment]
I'm having the same problem with the docker development image, isn't there a workaround this?

**Comment by whitef0x0** [comment]
@ersel you have set your BASE_URL parameter in the .env file.

**Comment by asmarius** [comment]
I ran `./scripts/setup.js` but it only created an empty .env file. Is that the correct behaviour?

**Comment by asmarius** [comment]
@whitef0x0 My subdomain is working but I'm ending up with 

`Page Not Found
	 is not a valid path.`

**Comment by dguzman1012** [comment]
I have the same probelm!!!! @asmarius @whitef0x0

**Comment by whitef0x0** [comment]
@asmarius what is the url that you get that error for?

**Comment by lucas-bremond** [comment]
I have the exact same problem.

I'm using the `tellform/app:stable` Docker image,

`.env` set as follows:

```
...
NODE_ENV=development
...
PORT=5000
...
BASE_URL=localhost
...
```

```
curl http://localhost:5000/forms
```

returns `401`.

Any idea?
