### ISSUE TITLE
Error examples

### ISSUE THREAD

**Issue by jonathanAcute** [whitef0x0/tellform#145]
The examples website dont work :(

**Comment by stanfaire** [comment]
It seems to work now 👍

**Comment by hieuiee** [comment]
Same. Having issues viewing examples (502 bad gateway) & admin.tellform.com (cloudflare - bad gateway)

**Comment by gregordimi** [comment]
Same. Still not working

**Comment by sarbjeetsingh** [comment]
Example are not working

**Comment by whitef0x0** [comment]
@sarbjeetsingh @gregordimi @hieuiee Sorry about this. Just got everything up again.
