### ISSUE TITLE
Signup Form for password input not displaying ••• on MacOS Safari (CSS issue)

### ISSUE THREAD

**Issue by membranepotential** [whitef0x0/tellform#149]
Hey!

The signup field on MacOS (Desktop) Safari 10.0.3 has an issue. It works in Chrome for me. It doesn't display any input characters (•) on typing. Signup works anyway.

Deleting the `padding: 30px 20px;` for input.form-control in the developer tools fixes the issue, but then the inputs are too small, obviously.

Cheers =)

**Comment by whitef0x0** [comment]
This has been replicated. Will deploy hotfix for this shortly.

**Comment by whitef0x0** [comment]
Fixed and deployed.
