### ISSUE TITLE
submit-form.client.directive.js errors

### ISSUE THREAD

**Issue by rotragit** [whitef0x0/tellform#155]
I get several errors trying to run. I don't know if it's a dependency problem. 

Running "jshint:all" (jshint) task

   public/form_modules/forms/base/directives/submit-form.client.directive.js
    171 |                                    return !(left.indexOf(right) > -1);
                                                    ^ Confusing use of '!'.
    215 |                            if(field_id == currField._id){
                                                   ^ Expected '===' and instead saw '=='.
    322 |                    }
                              ^ Missing semicolon.
    337 |                    }
                              ^ Missing semicolon.

**Comment by rotragit** [comment]
Ubuntu 16.04.2 LTS
nodejs v4.2.6
npm 3.5.2
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by whitef0x0** [comment]
@rotragit the jshint errors should be fine. Is it stopping you from running the grunt task?

**Comment by rotragit** [comment]
Hi, sorry, I was out of office and I'll check again on Monday. Anyway I have got only a blank page when browsing to http://localhost:3000. I'll check again also the configuration.
Thank you!

**Comment by rotragit** [comment]
Hi, grunt test fails with:

  Form Routes Unit tests
    1)  > should be able to upload a PDF to Form if signed in
    ✓  > should not be able to create a Form if not logged in
    ✓  > should not be able to get list of users' Forms if not logged in
Mon, 03 Apr 2017 07:39:31 GMT uncaughtException: Cannot read property
'should' of undefined
TypeError: Cannot read property 'should' of undefined
    at Test.<anonymous>
(/home/romano/tellform/app/tests/form.server.routes.test.js:147:34)
    at Test.assert
(/home/romano/tellform/node_modules/supertest/lib/test.js:156:6)
    at assert
(/home/romano/tellform/node_modules/supertest/lib/test.js:127:12)
    at /home/romano/tellform/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback
(/home/romano/tellform/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous>
(/home/romano/tellform/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

**Comment by whitef0x0** [comment]
@rotragit your branch is up to date with the current master right?

**Comment by rotragit** [comment]
On last Friday :-)

Il 03 apr 2017 2:43 PM, "David Baldwynn" <notifications@github.com> ha
scritto:

**Comment by whitef0x0** [comment]
@rotragit come on the gitter chat when your free so I can ask you more

**Comment by rotragit** [comment]
Ok, thank you David. I'll back in office on wednesday and I'll come in
gitter chat. I am from Europe (GMT+1). So, first I'll try a fresh install
again and move on a server and not my PC, so I can contact you from home,
in the evening (forse me ;-) )

Romano



Il 03 apr 2017 6:13 PM, "David Baldwynn" <notifications@github.com> ha
scritto:

@rotragit <https://github.com/rotragit> come on the gitter chat when your
free so I can ask you more

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/whitef0x0/tellform/issues/155#issuecomment-291192346>,
or mute the thread

**Comment by rotragit** [comment]
Hi, I've deleted the project and cloned again the master. I've got much less errors due to previously missing dependencies. Now grunt gives:

Running "concurrent:default" (concurrent) task
Fatal error: watch public/modules/core/views/header.client.view.html ENOSPC
romano@romano-Vostro-3350:~/tellform$ 

I'm on gitter chat now, anyway.

**Comment by whitef0x0** [comment]
@rotragit this means you have run out of space on your server/computer. See https://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by rotragit** [comment]
@whitef0x0

ok,

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
&& sudo sysctl -p


solved :-)


...and...now running fine! Thank you!!

**Comment by whitef0x0** [comment]
@rotragit awesome! Let me know if you have any other problems.

**Comment by whitef0x0** [comment]
@rotragit Also, if you like TellForm and want to support it donations are always welcome (to fund server and development costs).

You can donate here http://opencollective.com/tellform
