### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by rotragit** [whitef0x0/tellform#157]
When I create a form, the first input is OK, but as I try to add a second input of any type, I get:

Segmentation fault (core dumped)
    [nodemon] app crashed - waiting for file changes before starting...

Sometime restarting the server the action is saved, sometime it is not.

Let me know any log or info you need to know....

Thank you!

**Comment by whitef0x0** [comment]
@rotragit Sounds like a c compuler problem. Did you have an issues with the npm install?

**Comment by whitef0x0** [comment]
What OS are you running this on again? And what version of gcc/g++ ?

**Comment by rotragit** [comment]
@whitef0x0 here you have the output of npm install:

romano@romano-Vostro-3350:~/tellform$ npm install

> TellForm@2.0.0 postinstall /home/romano/tellform
> bower install --config.interactive=false; grunt build;

bower extra-resolution      Unnecessary resolution:
angular-ui-select#compiled
Running "jshint:all" (jshint) task

   public/form_modules/forms/base/directives/submit-form.client.directive.js
      5 |jsep.addBinaryOp("contains", 10);
                                    ^ Strings must use singlequote.
      6 |jsep.addBinaryOp("!contains", 10);
                                     ^ Strings must use singlequote.
      7 |jsep.addBinaryOp("begins", 10);
                                  ^ Strings must use singlequote.
      8 |jsep.addBinaryOp("!begins", 10);
                                   ^ Strings must use singlequote.
      9 |jsep.addBinaryOp("ends", 10);
                                ^ Strings must use singlequote.
     10 |jsep.addBinaryOp("!ends", 10);
                                 ^ Strings must use singlequote.
     34 |        return ("0000000" + (hval >>> 0).toString(16)).substr(-8);
                                  ^ Strings must use singlequote.
    139 |                            right = logicJump.valueB
                                                             ^ Missing
semicolon.
    171 |                                    return !(left.indexOf(right) >
-1);
                                                    ^ Confusing use of '!'.
    215 |                            if(field_id == currField._id){
                                                   ^ Expected '===' and
instead saw '=='.
    322 |                    }
                              ^ Missing semicolon.
    327 |                    $.ajaxSetup( { "async": false } );
                                                   ^ Strings must use
singlequote.
    329 |                    $.ajaxSetup( { "async": true } );
                                                   ^ Strings must use
singlequote.
    337 |                    }
                              ^ Missing semicolon.
      5 |jsep.addBinaryOp("contains", 10);
         ^ 'jsep' is not defined.
      6 |jsep.addBinaryOp("!contains", 10);
         ^ 'jsep' is not defined.
      7 |jsep.addBinaryOp("begins", 10);
         ^ 'jsep' is not defined.
      8 |jsep.addBinaryOp("!begins", 10);
         ^ 'jsep' is not defined.
      9 |jsep.addBinaryOp("ends", 10);
         ^ 'jsep' is not defined.
     10 |jsep.addBinaryOp("!ends", 10);
         ^ 'jsep' is not defined.
    134 |                        var parse_tree =
jsep(logicJump.expressionString);
                                                  ^ 'jsep' is not defined.
    308 |                    var md = new
MobileDetect(window.navigator.userAgent);
                                          ^ 'MobileDetect' is not defined.
    327 |                    $.ajaxSetup( { "async": false } );
                             ^ '$' is not defined.
    328 |                    var geoData = $.getJSON('
https://freegeoip.net/json/').responseJSON;
                                           ^ '$' is not defined.
    329 |                    $.ajaxSetup( { "async": true } );
                             ^ '$' is not defined.
   public/form_modules/forms/base/services/socket.io.client.service.js
     21 |        console.log("$window.socketPort: "+$window.socketPort);
                                                   ^ Strings must use
singlequote.
     22 |        console.log("$window.socketUrl: "+$window.socketUrl);
                                                  ^ Strings must use
singlequote.
     38 |            service.socket = io(url, {'transports': ['websocket',
'polling']});
                                      ^ 'io' is not defined.

 public/form_modules/forms/directives/analytics-service.client.directive.js
     31 |            $.ajaxSetup( { "async": false } );
                                           ^ Strings must use singlequote.
     33 |            $.ajaxSetup( { "async": true } );
                                           ^ Strings must use singlequote.
     40 |                }
                          ^ Missing semicolon.
     20 |            var md = new MobileDetect(userAgentString);
                                  ^ 'MobileDetect' is not defined.
     31 |            $.ajaxSetup( { "async": false } );
                     ^ '$' is not defined.
     32 |            var geoData = $.getJSON('
https://freegeoip.net/json/').responseJSON;
                                   ^ '$' is not defined.
     33 |            $.ajaxSetup( { "async": true } );
                     ^ '$' is not defined.
   public/modules/core/services/socket.io.client.service.js
     26 |            service.socket = io(url, {'transports': ['websocket',
'polling']});
                                      ^ 'io' is not defined.
   public/modules/forms/admin/controllers/admin-form.client.controller.js
     26 |        $scope.formURL = "/#!/forms/" + $scope.myform._id;
                                              ^ Strings must use
singlequote.
     28 |        if($window.subdomainsDisabled == true){
                                                 ^ Expected '===' and
instead saw '=='.
   public/modules/forms/admin/controllers/list-forms.client.controller.js
     32 |                    }
                              ^ Missing semicolon.
   public/modules/forms/admin/directives/auto-save.client.directive.js
     90 |                    var changedFields =
!!DeepDiff.diff(oldValue.form_fields, newValue.form_fields) &&
DeepDiff.diff(oldValue.form_fields, newValue.form_fields).length > 0;
                                                   ^ 'DeepDiff' is not
defined.
     90 |                    var changedFields =
!!DeepDiff.diff(oldValue.form_fields, newValue.form_fields) &&
DeepDiff.diff(oldValue.form_fields, newValue.form_fields).length > 0;

                                    ^ 'DeepDiff' is not defined.
    125 |                            var _diff = DeepDiff.diff(oldValue,
newValue);
                                                 ^ 'DeepDiff' is not
defined.
   public/modules/forms/admin/directives/edit-form.client.directive.js
     25 |                            if(!err)
$scope.myform.form_fields.push(newField);

 ^ 'newField' is not defined.

 public/modules/forms/admin/directives/edit-submissions-form.client.directive.js
     55 |                            if(numSubmissions == 0) return 0;
                                                         ^ Expected '==='
and instead saw '=='.
    108 |                $scope.$on("$destroy", function() {
                                              ^ Strings must use
singlequote.
   public/modules/forms/base/services/socket.io.client.service.js
     36 |            service.socket = io(url, {'transports': ['websocket',
'polling']});
                                      ^ 'io' is not defined.

 public/modules/forms/tests/unit/directives/edit-form.client.directive.test.js
     92 |            }
                      ^ Missing semicolon.
   config/env/all.js
     18 |        "accessKeyId": process.env.AWS_ACCESS_ID,
                              ^ Strings must use singlequote.
     19 |        "secretAccessKey": process.env.AWS_SECRET_KEY,
                                  ^ Strings must use singlequote.
     20 |        "region": process.env.AWS_REGION
                         ^ Strings must use singlequote.
     30 |    signupDisabled: (process.env.SIGNUP_DISABLED === "TRUE"),
                                                                    ^
Strings must use singlequote.
     39 |    subdomainsDisabled: (process.env.SUBDOMAINS_DISABLED ==
"TRUE"),

 ^ Strings must use singlequote.
     39 |    subdomainsDisabled: (process.env.SUBDOMAINS_DISABLED ==
"TRUE"),
                                                                    ^
Expected '===' and instead saw '=='.
   config/express.js
     99 |                if(process.env.NODE_ENV == 'development'){
                                                   ^ Expected '===' and
instead saw '=='.
    146 |                console.log("path: " + path);
                                             ^ Strings must use singlequote.
    156 |            var urlPath = url.parse(req.url).path.split('/');
                         ^ 'urlPath' is already defined.
   config/passport_helpers.js
      1 |"use strict";
                     ^ Strings must use singlequote.
      3 |var config = require("./config");
                                        ^ Strings must use singlequote.
      4 |var passport = require("passport");
                                          ^ Strings must use singlequote.
     14 |            passport.authenticate("localapikey", function (err,
user, info) {
                                                        ^ Strings must use
singlequote.
     19 |                    return res.status(401).send(info.message ||
"");

 ^ Strings must use singlequote.
     38 |        throw new Error("Required role needs to be set");
                                                                ^ Strings
must use singlequote.
     51 |    return module.exports.hasRole("admin");
                                                  ^ Strings must use
singlequote.
   config/socket.io.js
     18 |    if(process.env.DISABLE_CLUSTER_MODE !== "TRUE"){
                                                           ^ Strings must
use singlequote.
   config/strategies/apikey.js
      1 |"use strict";
                     ^ Strings must use singlequote.
      3 |var passport = require("passport");
                                          ^ Strings must use singlequote.
      4 |var LocalAPIKeyStrategy =
require("passport-localapikey-update").Strategy;
                                                                        ^
Strings must use singlequote.
     12 |            "apiKey": apiKey
                             ^ Strings must use singlequote.
     19 |                    message: "Unknown API Key"
                                                       ^ Strings must use
singlequote.
   app/controllers/forms.server.controller.js
     53 |    if(typeof req.body.timeElapsed == "number"){
                                                       ^ Strings must use
singlequote.
     53 |    if(typeof req.body.timeElapsed == "number"){
                                              ^ Expected '===' and instead
saw '=='.
    118 |            message: "Invalid Input"
                                             ^ Strings must use singlequote.
    216 |        if(form.analytics == null){
                                     ^ Expected '===' and instead saw '=='.
   app/controllers/users/users.authentication.server.controller.js
     15 |    tokgen = require("../../libs/tokenGenerator");
                                                         ^ Strings must use
singlequote.
   app/controllers/users/users.password.server.controller.js
     69 |                name: user.displayName || "TellForm User",
                                                                  ^ Strings
must use singlequote.
    149 |                                done(err, null)
                                                        ^ Missing semicolon.
    157 |                    done('Password reset token is invalid or has
expired.', null)

              ^ Missing semicolon.
    183 |        debugger;
                 ^ Forgotten 'debugger' statement?
    191 |            message: "Successfully changed your password!"
                                                                   ^
Strings must use singlequote.
   app/libs/tokenGenerator.js
      1 |"use strict";
                     ^ Strings must use singlequote.
      3 |var TokenGenerator = require("uuid-token-generator");
                                                            ^ Strings must
use singlequote.
   app/models/form.server.model.js
    224 |    if(this.form_fields.length == 0) return null;
                                          ^ Expected '===' and instead saw
'=='.

>> 82 errors in 140 files
Warning: Task "jshint:all" failed. Used --force, continuing.

Running "jshint:allTests" (jshint) task
>> 6 files lint free.

Running "csslint:all" (csslint) task
Linting public/modules/forms/admin/css/edit-form.css...ERROR
[GENERAL]
WARNING: Fallback background (hex or RGB) should precede RGBA background.
For older browsers that don't support RGBA, HSL, or HSLA, provide a
fallback color. (fallback-colors) Browsers: IE6,IE7,IE8
Linting public/modules/forms/base/css/form.css...ERROR
[GENERAL]
WARNING: Outlines shouldn't be hidden unless other visual changes are made.
Use of outline: none or outline: 0 should be limited to :focus rules.
(outline-none) Browsers: All
[GENERAL]
WARNING: Rule is empty. Rules without any properties specified should be
removed. (empty-rules) Browsers: All
Linting public/modules/users/css/users.css...ERROR
[GENERAL]
WARNING: Missing vendor-prefixed CSS gradients for Old Webkit (Safari 4+,
Chrome), Opera 11.1+. When using a vendor-prefixed gradient, make sure to
use them all. (gradients) Browsers: All
Linting public/form_modules/forms/base/css/form.css...ERROR
[GENERAL]
WARNING: Outlines shouldn't be hidden unless other visual changes are made.
Use of outline: none or outline: 0 should be limited to :focus rules.
(outline-none) Browsers: All
>> 9 files lint free.

Running "loadConfig" task
NODE_ENV is not defined! Using default development environment

Running "cssmin:combine" (cssmin) task
>> 1 file created. 28.43 kB → 18.38 kB

Running "ngAnnotate:production" (ngAnnotate) task
>> 2 files successfully generated.

Running "uglify:production" (uglify) task
>> 2 files created.

Running "html2js:main" (html2js) task
Successfully converted 39 html templates to js.

Running "html2js:forms" (html2js) task
Warning:
public/form_modules/forms/base/views/directiveViews/field/textfield.html
Error: Parse Error: <input ng-style="{'color': design.colors.answerColor,
'border-color': design.colors.answerColor}"
name="{{field.fieldType}}{{index}}"
            type="{{input_type}}"
  ng-pattern="validateRegex"
placeholder="{{placeholder}}"
ng-class="{ 'no-border': !!field.fieldValue }"
            class="focusOn text-field-input"
ng-model="field.fieldValue"
ng-model-options="{ debounce: 250 }"
value="field.fieldValue"
   ng-focus="setActiveField(field._id, index, true)"
  on-enter-or-tab-key="nextField()"
  on-tab-and-shift-key="prevField()"
ng-required="field.required"
ng-disabled="field.disabled"
       aria-describedby="inputError2Status"/ >
    </div>
    <div class="col-xs-12">
        <div ng-show="forms.myForm.{{field.fieldType}}{{index}}.$invalid &&
!!forms.myForm.{{field.fieldType}}{{index}}.$viewValue " class="alert
alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign"
aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
<span ng-if="field.fieldType == 'email'"> {{ 'ERROR_EMAIL_INVALID' |
translate }} </span>
<span ng-if="field.validateRegex"> {{ 'ERROR_NOT_A_NUMBER' | translate }}
</span>
<span ng-if="field.fieldType == 'link'"> {{ 'ERROR_URL_INVALID' | translate
}} </span>
        </div>
    </div>
</div>
<div>
<div class="btn btn-lg btn-default col-xs-12 col-sm-4 hidden-xs"
style="padding: 4px; margin-top:8px; background: rgba(255,255,255,0.5)">
<button ng-disabled="!field.fieldValue ||
forms.myForm.{{field.fieldType}}{{$index}}.$invalid"
ng-style="{'background-color':design.colors.buttonColor,
'color':design.colors.buttonTextColor}"
                ng-click="nextField()"
class="btn col-sm-5 col-xs-5">

{{ 'OK' | translate }} <i class="fa fa-check"></i>
</button>
<div class="col-xs-6 col-sm-3" style="margin-top:0.2em">
<small style="color:#ddd; font-size:70%">
{{ 'ENTER' | translate }}
</small>
</div>
</div>
</div> Used --force, continuing.
Successfully converted 14 html templates to js.

Done, but with warnings.
- redeyed node_modules/bower/node_modules/cardinal/node_modules/redeyed
- touch node_modules/bower/node_modules/decompress-zip/node_modules/touch
- os-name node_modules/bower/node_modules/insight/node_modules/os-name
- win-release
node_modules/bower/node_modules/insight/node_modules/os-name/node_modules/win-release
TellForm@2.0.0 /home/romano/tellform
├─┬ bower@1.6.9
│ ├─┬ bower-registry-client@1.0.0
│ │ └── lru-cache@2.7.3
│ ├── cardinal@0.4.4
│ ├─┬ configstore@0.3.2
│ │ └─┬ js-yaml@3.4.6
│ │   └─┬ argparse@1.0.3
│ │     └── lodash@3.10.1
│ ├─┬ decompress-zip@0.1.0
│ │ ├── mkpath@0.1.0
│ │ ├── readable-stream@1.1.14
│ │ └─┬ touch@0.0.3
│ │   └── nopt@1.0.10
│ ├── github@0.2.4
│ ├─┬ inquirer@0.10.0
│ │ ├── lodash@3.10.1
│ │ ├─┬ readline2@1.0.1
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ └── rx-lite@3.1.2
│ ├─┬ insight@0.7.0
│ │ ├─┬ configstore@1.4.0
│ │ │ ├── graceful-fs@4.1.11
│ │ │ └── uuid@2.0.3
│ │ └── object-assign@4.1.1
│ ├── lru-cache@2.7.3
│ └── nopt@3.0.6
├── cardinal@0.4.4  extraneous
├── decompress-zip@0.1.0  extraneous
├─┬ del@2.2.2
│ └── object-assign@4.1.1
├─┬ fs-extra@0.26.7
│ └── graceful-fs@4.1.11
├── github@0.2.4  extraneous
├─┬ grunt@0.4.5
│ └── nopt@1.0.10
├─┬ grunt-concurrent@2.3.1
│ └─┬ pad-stream@1.2.0
│   └─┬ meow@3.7.0
│     └── object-assign@4.1.1
├─┬ grunt-contrib-csslint@1.0.0
│ └── lodash@3.10.1
├─┬ grunt-contrib-jshint@1.0.0
│ └─┬ jshint@2.9.4
│   └─┬ htmlparser2@3.8.3
│     └── readable-stream@1.1.14
├─┬ grunt-karma@0.12.2
│ └── lodash@3.10.1
├─┬ grunt-node-inspector@0.4.2
│ └─┬ node-inspector@0.12.10
│   ├─┬ biased-opener@0.2.8
│   │ └─┬ browser-launcher2@0.4.6
│   │   └─┬ plist@1.2.0
│   │     └─┬ xmlbuilder@4.0.0
│   │       └── lodash@3.10.1
│   └─┬ v8-debug@0.7.7
│     └─┬ node-pre-gyp@0.6.34
│       └─┬ npmlog@4.0.2
│         └─┬ gauge@2.7.3
│           └── object-assign@4.1.1
├─┬ grunt-nodemon@0.4.2
│ └─┬ nodemon@1.11.0
│   └─┬ update-notifier@0.5.0
│     └─┬ configstore@1.4.0
│       ├── object-assign@4.1.1
│       └── uuid@2.0.3
├─┬ inquirer@1.2.3
│ └─┬ figures@1.7.0
│   └── object-assign@4.1.1
├── insight@0.7.0  extraneous
├─┬ istanbul@0.4.5
│ └── nopt@3.0.6
├─┬ karma@0.13.22
│ └── lodash@3.10.1
├─┬ karma-phantomjs-launcher@0.2.3
│ └── lodash@3.10.1
├─┬ main-bower-files@2.9.0
│ └─┬ vinyl-fs@1.0.0
│   └── graceful-fs@3.0.11
├─┬ multer@1.3.0
│ └─┬ busboy@0.2.14
│   ├─┬ dicer@0.2.5
│   │ └── readable-stream@1.1.14
│   └── readable-stream@1.1.14
├─┬ nightwatch@0.9.14
│ └─┬ proxy-agent@2.0.0
│   └─┬ pac-proxy-agent@1.0.0
│     └─┬ get-uri@1.1.0
│       └─┬ ftp@0.3.10
│         └── readable-stream@1.1.14
└─┬ supertest-session@2.0.1
  └── object-assign@4.1.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture:
fsevents@1.1.1
romano@romano-Vostro-3350:~/tellform$

**Comment by rotragit** [comment]
Ubuntu 16.04.2 LTS
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by whitef0x0** [comment]
@rotragit can you remove the npm_modules folder and then run 'npm install'

**Comment by whitef0x0** [comment]
Also can you run npm rebuild and then npm install and see if it works?

What version of npm/nodejs are you running?

**Comment by whitef0x0** [comment]
@rotragit seems like the error you are getting is due to a problem with node/npm and not with TellForm itself. Try going through this thread https://github.com/nodejs/node/issues/2763 and seeing if any of the solutions work for you.
