### ISSUE TITLE
heroku deploy results in empty repo when you try to clone it

### ISSUE THREAD

**Issue by coderbec** [whitef0x0/tellform#159]
Used heroku deploy button. 

Tried to clone onto my computer with heroku cli 

"heroku git:clone -a appname"

This clones an empty file with nothing in it

**Comment by whitef0x0** [comment]
@coderbec Seems like this fixes it. https://stackoverflow.com/questions/36621955/heroku-clone-creates-an-empty-folder/37497276#37497276
