### ISSUE TITLE
Add Storage/AWS to App

### ISSUE THREAD

**Issue by whitef0x0** [whitef0x0/tellform#17]
Currently user signup does not work as we can't create new folders in heroku instance. Need to replace local storage with something like AWS S3

**Comment by whitef0x0** [comment]
Not sure if this is critical. Put this on the backlog.

**Comment by mkoegel** [comment]
Is there a workaround to get tellform working on Heroku?
If not maybe remove the deploy to Heroku button as it's not very useful right now.

**Comment by whitef0x0** [comment]
The dev branch deploys on heroku. I am in the middle of exams but will fix the master branch soon

**Comment by whitef0x0** [comment]
This is related to #75
