### ISSUE TITLE
Add Logic Jump/Multiple Form Pages

### ISSUE THREAD

**Issue by whitef0x0** [whitef0x0/tellform#24]
Need to add logic jump functionality for form inputs and/or add ability to have multiple pages per form.

**Comment by lalop** [comment]
Do you have any plan to merge this soon ?

**Comment by whitef0x0** [comment]
I have not really worked on this for a while and it is not near ready anytime soon

**Comment by lalop** [comment]
Do you have any idea of how to manage that ?
I will have to make a system like that, I'm interested into do it for tellform. You can find me on gitter if you want.

**Comment by whitef0x0** [comment]
@lalop I'm currently working on it on the logic_jump branch, which I'll push soon once I have a working version. I'm trying to use a graph database to store the Boolean Expressions in and then evaluating them on the fly

**Comment by lalop** [comment]
I implemented a kind of field logic here https://github.com/lalop/tellform/commit/34279baa92e2df045b05b1ebfb8f25f93f83ac4f
I wouldn't say it's the smartest solution but it's pretty flexible

**Comment by whitef0x0** [comment]
The hard part is implementing it on the backend, not the frontend.

**Comment by manuelramon** [comment]
Hi there guys, @whitef0x0 @lalop I would like to say that your project David is amazing, I'm just trying to install on my server and seems quite difficult for me, where can I get an easy guide to install on my environment? Once installed, I would like to test the LOGIC JUMPS if you want to have a beta tester, drop me a line, I'm at your entire  disposal guys.

**Comment by whitef0x0** [comment]
@manuelramon logic jump is currently not implemented.

You can run ''' node scripts/setup.js''' for setup

**Comment by whitef0x0** [comment]
@lalop @AdrianP- I've got this working on the api branch if you want to check it out

**Comment by lalop** [comment]
@whitef0x0 I will try to check next week

**Comment by whitef0x0** [comment]
@lalop sorry it's actually on the logic_jump branch

**Comment by MiloParigi** [comment]
@whitef0x0 is it actually in beta or a working feature ? Thanks for this awesome work btw !

**Comment by whitef0x0** [comment]
@MiloParigi this is a working feature on the logic jump branch

**Comment by whitef0x0** [comment]
@MiloParigi this has been merged and is live at tellform.com
