### ISSUE TITLE
Could not connect to MongoDB!

### ISSUE THREAD

**Issue by ahyear** [whitef0x0/tellform#47]
no matter what I do, ( i followed the install process ) when i want to "grunt default" i get 

Could not connect to MongoDB!
Error: failed to connect to [localhost:27017]

I tried replacing localhost with 127.0.0.1 but i get the same error...

here is what it says:

` Running "jshint:all" (jshint) task

   public/modules/forms/directives/auto-save.client.directive.js
     10 |        });
                  ^ Don't make functions within a loop.
   public/modules/forms/directives/edit-submissions-form.client.directive.js
     56 |                                    oldValue = data[i].form_fields[x].fieldValue || '';
                                             ^ 'oldValue' is not defined.
     58 |                                    data[i].form_fields[x].fieldValue = oldValue;
                                                                                 ^ 'oldValue' is not defined.
    114 |                    saveAs(blob, $scope.myform.title+'_sumbissions_export_'+Date.now()+'.'+type);
                             ^ 'saveAs' is not defined.
   public/modules/forms/directives/submit-form.client.directive.js
     49 |                        $('html, body').animate({
                                 ^ '$' is not defined.
     50 |                            scrollTop: $('.activeField').offset().top
                                                ^ '$' is not defined.
   gruntfile.js
    255 |                grunt.log.error("Failed to submit lcov file to coveralls: " + err);
                                                                                    ^ Strings must use singlequote.
    258 |            grunt.verbose.ok("Successfully submitted lcov file to coveralls");
                                                                                     ^ Strings must use singlequote.
   config/config.js
      6 |var _ = require('lodash'),
             ^ Redefinition of '_'.
   app/controllers/forms.server.controller.js
     15 |    _ = require('lodash');
             ^ Redefinition of '_'.
    187 |    console.log(req.body.form)
                                       ^ Missing semicolon.
   app/controllers/users.server.controller.js
      6 |var _ = require('lodash');
             ^ Redefinition of '_'.
   app/controllers/users/users.authentication.server.controller.js
      6 |var _ = require('lodash'),
             ^ Redefinition of '_'.
   app/controllers/users/users.authorization.server.controller.js
      6 |var _ = require('lodash'),
             ^ Redefinition of '_'.
   app/controllers/users/users.password.server.controller.js
      6 |var _ = require('lodash'),
             ^ Redefinition of '_'.
   app/controllers/users/users.profile.server.controller.js
      6 |var _ = require('lodash'),
             ^ Redefinition of '_'.
   app/models/form.server.model.js
      9 |    _ = require('lodash'),
             ^ Redefinition of '_'.
    437 |                            });
                                      ^ Don't make functions within a loop.
   app/models/form_field.server.model.js
      8 |    _ = require('lodash'),
             ^ Redefinition of '_'.
   app/models/form_submission.server.model.js
     10 |    _ = require('lodash'),
             ^ Redefinition of '_'.
   app/models/logic_jump.server.model.js
      8 |    _ = require('lodash'),
             ^ Redefinition of '_'.

>> 21 errors in 99 files
Warning: Task "jshint:all" failed. Used --force, continuing.
Running "jshint:allTests" (jshint) task
>> 7 files lint free.

Running "csslint:all" (csslint) task
Linting public/modules/core/css/select.css...ERROR
[L11:C1]
WARNING: Outlines should only be modified using :focus. Use of outline: none or outline: 0 should be limited to :focus rules. (outline-none) Browsers: All
[L13:C10]
WARNING: Values of 0 shouldn't have units specified. You don't need to specify units when a value is 0. (zero-units) Browsers: All
[L16:C18]
WARNING: Values of 0 shouldn't have units specified. You don't need to specify units when a value is 0. (zero-units) Browsers: All
[L104:C1]
>> ERROR: Unknown @ rule: @-moz-document. This rule looks for recoverable syntax errors. (errors) Browsers: All
Linting public/modules/forms/css/form.css...ERROR
[L66:C1]
WARNING: Outlines shouldn't be hidden unless other visual changes are made. Use of outline: none or outline: 0 should be limited to :focus rules. (outline-none) Browsers: All
[L286:C1]
WARNING: The properties margin-top, margin-bottom, margin-left, margin-right can be replaced by margin. Use shorthand properties where possible. (shorthand) Browsers: All
Warning: Task "csslint:all" failed. Used --force, continuing.

Running "html2js:main" (html2js) task
Successfully converted 46 html templates to js.

Running "concurrent:default" (concurrent) task
    Running "watch" task
    Waiting...
    Running "nodemon:dev" (nodemon) task
    [nodemon] 1.8.1
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
    [nodemon] starting `node --debug server.js`
    debugger listening on port 5858
    --
    TellForm application started
    Environment:                        development
    Port:                               3000
    Database:                   mongodb://localhost/mean-dev
    --
    Could not connect to MongoDB!
    Error: failed to connect to [localhost:27017]
`

**Comment by whitef0x0** [comment]
I'll look into this

**Comment by ahyear** [comment]
thank you, let me know if you need any specific info.

**Comment by whitef0x0** [comment]
This is mostly likely because either you have not installed or started your local mongodb instance.
