### ISSUE TITLE
Extract form ui

### ISSUE THREAD

**Issue by lalop** [whitef0x0/tellform#54]
Hello,
What do you think of extracting the form ui from the project and adding it as a dependency ?

**Comment by whitef0x0** [comment]
By form ui, are you referring to the submit-form and field directives that renders the forms?

**Comment by lalop** [comment]
Yes that what I mean

**Comment by whitef0x0** [comment]
Right now, my focus is on fixing the last few bugs in the UI to get it ready for use in beta. I do support modularization but I would rather spend the time migrating from mongoose/mongodb first and then look at modularization later.

**Comment by lalop** [comment]
HI @whitef0x0 ,
I've a working prototype but I can't keep it sync with yout repository.
I can make some refactor on the form module to have it usable alone but I need to know if your are okey with the way I will do it and of course if this interest you or not at all.

I've point two main issue :
* form edition and form submission are in the same module
* tellform api that is hard coded in the module

For the first point I can divide the module into two submodules, `base` with fields and all needed for viewer and `admin` with all edition related stuff.
For the sencond one I'm not sure for the moment of the way to go.

Let me know what do you think.
Thank you

**Comment by whitef0x0** [comment]
For the second point you could add a configuration file to add api hardpoints? Or you could just develop it without http requests.

**Comment by whitef0x0** [comment]
If we can make this into a module I think it would be quite useful for many ad I've had others request in the past for just the front end

**Comment by whitef0x0** [comment]
Maybe I should make a github org and we can make a new repo?

**Comment by lalop** [comment]
I don't use to use angular so I am not sure of the good way to extract the http part.
As I see it at the end submit-form should provide an api to display a form whenever the form data is loaded, to submit it more some sweets helpers to display only one filed ( for admin ), events...
To start I only need to load fields and save form, so I think we can say that when the form directive is called the form data is allready loaded.

The organisation sounds good for me

**Comment by whitef0x0** [comment]
Regarding form api endpoints I think this would be a good convention to follow https://formkeep.com

**Comment by lalop** [comment]
I don't know this service but I can't find any documentation on their website, do you have some ?

**Comment by whitef0x0** [comment]
Oh I didn't see that. I suggest for now you should only have one endpoint and use GET to fetch a json object with the form data and POST to submit the form. In tellform right now that's how I'm doing it. I just submit the same json file with completed form fields.

Seems the easiest way to do things. If you are curious at the format look at /app/models/form.server.models.js for the current schema.

Also out of curiosity are you going to develop this into an angular module? If you are before you embark I highly suggest you familiarize yourself with the framework.

I made a github repo for this here https://github.com/tellform/angular-tellform/tree/master and invited you.

**Comment by lalop** [comment]
merci :)

**Comment by whitef0x0** [comment]
Have you figured out how to create a webhook @lalop ?

**Comment by lalop** [comment]
see this https://github.com/whitef0x0/tellform/pull/59#issuecomment-215970911
but I didn't test it yet

**Comment by whitef0x0** [comment]
This has been finished @lalop in https://github.com/tellform/angular-tellform
