### ISSUE TITLE
error ui-router on master

### ISSUE THREAD

**Issue by lalop** [whitef0x0/tellform#64]
I have this error on master branch `Could not resolve 'home' from state 'listForms'`

**Comment by whitef0x0** [comment]
I've been making to fix this. This is because I deleted the home state

**Comment by whitef0x0** [comment]
*meaning

**Comment by lalop** [comment]
I'm not sure to understand, is that fixed or just you are aware of this issue ?

**Comment by whitef0x0** [comment]
It should be fixed in my most recent commit.
