### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by joekh** [whitef0x0/tellform#70]
I am not able to verify my email address on tellform.com

**Comment by jamesryanbell** [comment]
Hi

I also had this problem, the url in the email points to stage.tellform.com.

As a work around until this is fixed just change **stage.tellform.com** to **admin.tellform.com** and you should be fine.

Thanks,
James

**Comment by jamesryanbell** [comment]
Update:

Whilst this will say your account is activated, I am still struggling to sign in. 

Thanks,
James

**Comment by joekh** [comment]
Actually I was able to sign in after verifying my email (I used admin instead of stage)

But now i am struggling in creating a form, there's something wrong with the page, keeps refreshing i guess or something

**Comment by joekh** [comment]
![screen shot 2016-04-30 at 2 53 55 pm](https://cloud.githubusercontent.com/assets/844966/14935700/6c2f3fdc-0ee3-11e6-8381-95dff5fb137a.png)

**Comment by joekh** [comment]
I also managed to run the website on my own server, and still getting the same error above @jamesryanbell @whitef0x0

**Comment by joekh** [comment]
Hey guys @jamesryanbell @whitef0x0 any updates from your side?

**Comment by whitef0x0** [comment]
This has been fixed @joekh
