### ISSUE TITLE
Cannot create form

### ISSUE THREAD

**Issue by mkoegel** [whitef0x0/tellform#72]
Managed to get Tellform to run on my Mac after changing Mongoose from ^3.8.40 to ~3.8.40.
Otherwise I get mongoose 3.9.7 and tellform crashes on start.

Now I can sign-up, verify and login, but then the server loops between forms and favicon and I can't click the new form button.

Console output:

```
    GET /users/me 401 1.859 ms - 35
    GET /modules/core/img/brand/favicon.ico 304 0.524 ms - -
    POST /auth/signin 200 67.739 ms - 231
    GET /forms 401 2.248 ms - 35
    GET /modules/core/img/brand/favicon.ico 304 0.332 ms - -
    GET /forms 401 1.433 ms - 35
    GET /modules/core/img/brand/favicon.ico 304 0.381 ms - -
    GET /modules/core/img/brand/favicon.ico 304 0.311 ms - -
    GET /forms 401 1.752 ms - 35
```

How can I resolve this?

**Comment by lalop** [comment]
I made a pr for the first point https://github.com/whitef0x0/tellform/pull/71 but facing the same issue.
If you can fix it a pr is welcome otherwise you could try with an older commit maybe.
David created a gitter channel for this project if you're interested is here https://gitter.im/whitef0x0/tellform

**Comment by lalop** [comment]
The issue seems to come from the session module. The user isn't authenticated from the cookie.
Changing the session policy here https://github.com/whitef0x0/tellform/blob/master/config/express.js#L119 to  `app.use(session({secret: 'test'}));` made the app work again.

**Comment by joekh** [comment]
Hello @lalop I tried to replace the L119 with app.use(session({secret: 'test'})); but i am still having the same issue GET /forms 401 please advise

**Comment by lalop** [comment]
this work for me once I checkout to `22b4d695705c5cf056abfaf345498ff8f28f6b30`

**Comment by joekh** [comment]
@lalop  does this commit 22b4d695705c5cf056abfaf345498ff8f28f6b30 contains the upload file field?

**Comment by lalop** [comment]
I don't think no

**Comment by joekh** [comment]
@lalop the thing I really need a working version with the upload file field enabled, If you can help me I would appreciate it. Merci en avance

**Comment by lalop** [comment]
Not sure that I will be really helpfull but you can come on the gitter channel to speak of your issue and try to fix the project

**Comment by whitef0x0** [comment]
@joekh upload file field is currently not implemented

**Comment by whitef0x0** [comment]
I'm closing this issue as it seems like the original issue has been fixed by #71. 

@joekh you can check on the progress of the upload file field at #75

**Comment by coderbec** [comment]
I'm having this issue with the current version

**Comment by whitef0x0** [comment]
@coderbec you have to set your BASE_URL to localhost or whatever url you are using.

**Comment by whitef0x0** [comment]
@coderbec in your case, since you are using heroku, your BASE_URL should be set to my_app_name.herokuapp.com. You can set this in the **Config Vars** section of the **Settings** pane .

**Comment by coderbec** [comment]
it's definitely set

**Comment by whitef0x0** [comment]
@coderbec try pulling from the code again. I removed the domain in the config so it shouldn't happen anymore.

**Comment by whitef0x0** [comment]
@coderbec it's probably easier if you come on the gitter chat
