### ISSUE TITLE
Create OAuth API

### ISSUE THREAD

**Issue by whitef0x0** [whitef0x0/tellform#77]

**Comment by whitef0x0** [comment]
see this for inspiration https://news.ycombinator.com/item?id=11971491

**Comment by devkhan** [comment]
Any progress on this? Or is there is any other way to extend tellform?

**Comment by whitef0x0** [comment]
@devkhan I currently have a working api here https://github.com/whitef0x0/tellform/tree/api, but it isn't stable enough for master (yet).

It's not oauth, as it requires you to send the key in every request, but its a start.

**Comment by devkhan** [comment]
Is it possible to make login compulsory for submitting the form, yet?

It's not possible without OAuth, right?

**Comment by whitef0x0** [comment]
@devkhan that would be a complete deviation from what tellform is for (open forms). If you really ant to make login compulsary you could always protect your hosted instance with HTTP basic auth or something.

**Comment by whitef0x0** [comment]
@devkhan maybe before asking questions here you should read up on this https://stormpath.com/blog/what-the-heck-is-oauth.

**Comment by whitef0x0** [comment]
@devkhan this has been completed.
