### ISSUE TITLE
Start production

### ISSUE THREAD

**Issue by mmihalev** [whitef0x0/tellform#83]
Where is the grunt production task? I can't start it.

**Comment by whitef0x0** [comment]
Production and development is controlled by the NODE_ENV variable in your .env file

**Comment by whitef0x0** [comment]
just add NODE_ENV=production and then run grunt

**Comment by mmihalev** [comment]
Thanks @whitef0x0
Then readme should be updated. Because currently it says:
To run development version:

$ grunt default

To run production version:

$ grunt production

**Comment by whitef0x0** [comment]
Fixed
