### ISSUE TITLE
Add ability to send form to list of user with token

### ISSUE THREAD

**Issue by fixlair** [whitef0x0/tellform#84]
Hello !
It would be very great if we could send the form to a list of user (by mail) for example with a specific token so that every user can respond only one time to the survey.

Thanks a lot !
Thanks for the great project !

**Comment by whitef0x0** [comment]
What exactly do you mean by token?

**Comment by fixlair** [comment]
Hi !
By "token" I mean something uniq. In fact the idea was to be able to use Tellform as a survey tool in a restricted circle. Let's say that I have 10 users I would like to send them (by mail for example) a specific uniq link for each of them so that they will be able to answer the survey (nevermind they answer it or not, the important thing is just that they not may answer twice or more to make the survey revelant)

**Comment by whitef0x0** [comment]
This isn't  a core feature of a web form so Im closing this issue. If you want to fork this project and add ot you are more than welcome to do so
