### ISSUE TITLE
form does not continue on click of a star rating

### ISSUE THREAD

**Issue by lsascha** [whitef0x0/tellform#90]
the form continues scrolling down on click on nearly every field except the star rating parts. If i click on a star it stays there and i have to scroll down manually.

Additionally the next field will stay grayed out until i scrolled the next field to the top corner of the browser window, which feels a bit late so you might think it will stay inactive which makes the manual need to scroll worse.

**Comment by whitef0x0** [comment]
I will get to this by the weekend.

**Comment by whitef0x0** [comment]
This has been fixed. See demo form on tellform.com
