### ISSUE TITLE
Problem in setup

### ISSUE THREAD

**Issue by AdrianP-** [whitef0x0/tellform#93]
I get this when I try node ./scripts/setup.js:

```
sudo node ./scripts/setup.js

process.env.MAILER_EMAIL_ID: undefined
/home/tit/tellform/node_modules/email-verification/index.js:153
    return callback(null, options);
           ^

TypeError: callback is not a function
```

**Comment by whitef0x0** [comment]
What version of node are you running? Did you run npm install before running the setup script?

**Comment by whitef0x0** [comment]
You shouldn't be getting this error now.

**Comment by AdrianP-** [comment]
Yes, I still get the error. My platform is a ubuntu 14.04 server and node v6.2.0. 

Yes, I ran npm install before running the setup script. Also with a new dowload get this: 
`{ Error: Cannot find module '../build/Release/bson'` But this is fixed changed "mongoose": "3.8.40" with "mongoose": "^3.8.40" in package.json and reinstalling.

**Comment by whitef0x0** [comment]
I currently haven't tested it with node v6.2.0, so I can't guarantee it will work.

**Comment by AdrianP-** [comment]
But my first try was with 4.x version of node and I got the same error.

**Comment by whitef0x0** [comment]
What does your ```app/controllers/users/users.authentication.server.controller.js``` contain?

**Comment by whitef0x0** [comment]
oh wait

**Comment by whitef0x0** [comment]
Sorry I forgot to push the fixed changes to master. They are pushed now.

**Comment by AdrianP-** [comment]
I retry right now with the new push and the new error: 
```
/tellform/node_modules/email-verification/index.js:195
    return callback(null, mongoose.model(options.tempUserCollection));
           ^

TypeError: callback is not a function
```

**Comment by whitef0x0** [comment]
@AdrianP- sorry about this. I tested it on my system and the setup script now works. Just had to fix something else in my project.

**Comment by whitef0x0** [comment]
Let me know if it works for you as well.

**Comment by whitef0x0** [comment]
@AdrianP-

**Comment by AdrianP-** [comment]
It works!! Thank so much @whitef0x0 :)

**Comment by whitef0x0** [comment]
Awesome! Let me know if you have any other issues.

**Comment by AdrianP-** [comment]
Sorry  to be a pain but everything went ok until I run it and tried to log in:

![captura de pantalla 2016-06-04 a las 13 40 46](https://cloud.githubusercontent.com/assets/8615608/15799366/60c3c46e-2a5a-11e6-949d-41fcacff4eee.png)

**Comment by whitef0x0** [comment]
did you set the BASE_URL parameter?

**Comment by whitef0x0** [comment]
If it's not set, the domain of the sessionCookie won't be set and it won't work. In your case you need to set your session cookie to http://40.69.47.126

**Comment by AdrianP-** [comment]
Fix it. But the awesome script setup.js don't write the configurations in some .env file, so I had to create .env file with a correct BASE_URL.

I hope this is the last close :D

**Comment by whitef0x0** [comment]
Finding bugs makes the software better so don't feel bad about it! I'll look into fixing the setup script bug

**Comment by whitef0x0** [comment]
@AdrianP- did you get it to run?

**Comment by AdrianP-** [comment]
Sorry, I didn't test it. I will test in some moment. 
On the other hand, in "Multiple Choice" field, the user only can select one choice.

Where I can write new Fields? Have you some UML or Architecture Diagrams?

**Comment by whitef0x0** [comment]
I don't have UML or Architecture Diagrams but I can write those up for you if you like

**Comment by whitef0x0** [comment]
The Multiple Choice field is more like a radio field. See typeform for what I was going for.

**Comment by whitef0x0** [comment]
@AdrianP- To add a field, create a template for it here https://github.com/whitef0x0/tellform/tree/master/public/modules/forms/views/directiveViews/field/

Fields are rendered by this directive https://github.com/whitef0x0/tellform/blob/master/public/modules/forms/directives/field.client.directive.js.

On the server side, this is the model for storing the fields https://github.com/whitef0x0/tellform/blob/master/app/models/form_field.server.model.js. 

If you want to add a field, you should add your fieldname to the enum of fieldType in this file, as well as to the supported_fields array in https://github.com/whitef0x0/tellform/blob/master/public/modules/forms/directives/field.client.directive.js

**Comment by AdrianP-** [comment]
Don't worry about the Diagrams, the last comment help me a lot!
I want to code my own fields, so I hope to make some commits in the future.
I know nodejs, but it's my first time in Angular, so it will be gradually

**Comment by whitef0x0** [comment]
@AdrianP- you can reach me on email or on gitter if you need more help

**Comment by whitef0x0** [comment]
btw I think I fixed the .env bug in the setup script
