### ISSUE TITLE
margin issue

### ISSUE THREAD

**Issue by lalop** [whitef0x0/tellform#99]
There is an margin issue, the submit button can go out of the window, it seems to come from the bottom line.
<img width="1280" alt="capture d ecran 2016-06-01 a 21 20 40" src="https://cloud.githubusercontent.com/assets/313117/15722612/e068ed02-283e-11e6-9f38-f43afc4039ae.png">

**Comment by whitef0x0** [comment]
I'll look into it

**Comment by whitef0x0** [comment]
This has been fixed in the most recent commit

**Comment by lalop** [comment]
now the button's zone is smaller then the window 
<img width="1279" alt="capture d ecran 2016-06-05 a 02 05 32" src="https://cloud.githubusercontent.com/assets/313117/15802855/2cc77800-2ac2-11e6-88bc-2e73f095c950.png">

and the margin is bigger
<img width="1280" alt="capture d ecran 2016-06-05 a 02 07 13" src="https://cloud.githubusercontent.com/assets/313117/15802857/40fa48ac-2ac2-11e6-8393-0a972593e5c2.png">

**Comment by whitef0x0** [comment]
what should it ultimately look like? 

Btw the css code is in forms.css if you wish to modify it

**Comment by whitef0x0** [comment]
Can you share a screenshot of what it should look like?

**Comment by lalop** [comment]
I'm not sure of what you wanted to do but I imagine the idea is to have the submit button in the left top corner and no more scrolldown at this point.
Like this 
<img width="812" alt="capture d ecran 2016-06-05 a 11 48 07" src="https://cloud.githubusercontent.com/assets/313117/15804738/747bad46-2b13-11e6-9ef9-aaed23bf5837.png">
